---
knit: "bookdown::render_book"
---

# Pre-Registration Abstract {-}
\chaptermark{Abstract} <!-- Bug in template would put wrong chaptermark here, needs proper fix -->

The gold standard in the research of human concept and category learning are the six problem types introduced by @Shepard1961. More recent researched based on their seminal work showed a major influence of rule-related language having an effect in subject's performance on those problems [@Kurtz2013]: the long held learning advantage in solving Type II category structures over Type IV structures disappears when experimental instructions don't use the mentioning of rules.

Furthermore, @CK17 were able to show in a novel experimental adaptation to the classic SHJ-setup that there appear to be (at least) two rather distinct types of rule or concept learners: people who categorize novel stimuli in a way that resolves to a full XOR solution (equivalent to the Type II problem in SHJ) and those who classify the novel stimuli to the more proximal categories previously learned in a training phase.
Finally, @Schlegelmilch2021 proposed that extrapolating XOR category structures can be explained by contextual modulation; a cognitive mechanism by which conditional hypotheses are based on (previously learned) simple rules that can be applied depending of contextual stimuli (e.g., another stimulus feature), leading to better or easier classification given a more complex rule. Consequently, with their Category Abstraction Learning model (CAL) they suggest that extrapolation to a full-XOR solution in an incomplete-XOR task is a result of conditional hypotheses of simple rules.

According to the findings of @Kurtz2013, instructions mentioning rules facilitate learning of an exclusive-or rule structure, which they have shown for the classic Type II problem. Here, we posit that this effect, according to CAL, should also facilitate extrapolation in an incomplete-xor task. In more detail, according to CAL, rule instructions (compared to neutral instructions) increase the precision/strength with which rules are learned, which predicts quicker XOR learning and more frequent XOR extrapolation in the incomplete XOR transfer task. An analogue effect (quicker learning of simple rules) should be induced if, during learning, a simple rule is established before stimuli are introduced that require rule modulation for correct classification (blocked rule), compared to mixing these stimuli throughout (mixed rule). 

\newpage
