---
title: 'On the role of rule instructions and ordering'
subtitle: 'in category learning'
thesistype: 'Masterarbeit'
author:
  name: 'Anton, Tobias'
  birthday: "07.10.1985"
  birthplace: "Ankum"
  # degree: 'B.Sc.'
  matr: 979031
  adress: Emmastr. 281, 28213 Bremen
supervisorA: Dr. René Schlegelmilch
supervisorB: Dr. habil. Annette Hohenberger
date: '`r format(Sys.Date(), "%d.%m.%Y")`'
faculty: "8: Humanwissenschaften"
institute: "Institut für Kognitionswissenschaft"
# logo: "includes/LogoUniOsna.pdf"
bibliography: "bib/thesis.bib"
# csl: bib/apa.csl
mainfont: 'Lato'
# sansfont: 'PT Serif'
sansfont: 'Lato'
monofont: 'Fira Code'
mathfont: 'Asana Math'
site: bookdown::bookdown_site
link-citations: true
erklaerung: "includes/declaration.pdf"
deckblatt: true
verzeichnisse:
  toc: true
  figures: false
  tables: false
output:
  jermd::masterthesis:
    latex_engine: xelatex
    dev: cairo_pdf
    fig_caption: yes
    fig_height: 3
    fig_width: 5
    keep_tex: yes
    number_sections: yes
    pandoc_args: [
      "--top-level-division=chapter"
    ]
    citation_package: biblatex
knit: "bookdown::render_book"
---

<!--
Edit these lines as appropriate.
The actual thesis content is in several Rmd files.

You'll need to edit the _bookdown.yml file to set the order in which you'd like them to appear.


**Notice**: This file has to be named `index.Rmd`. If you created it from the RStudio template picker thingy and gave it a filename, you'll have to rename it.

Maybe I'll figure out how to fix this, sorry. -->

```{r init_options, message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(dplyr)
library(tidyr)
library(bridgesampling)
library(effectsize)
library(ggplot2)
library(patchwork)
# library(xtable)
library(kableExtra)

options(knitr.table.format = "latex",
        tinytex.verbose = TRUE)
knitr::opts_chunk$set(
  cache = FALSE,
  error = FALSE,
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  # fig.width = 8,
  fig.asp = 1/1.618,
  fig.align = "center",
  out.width = "90%",
  comment = "#>",
  tidy = FALSE # "formatR",
  # tidy.opts = list(blank = FALSE, width.cutoff = 80)
)

theme_set(hrbrthemes::theme_ipsum_ps(
    plot_margin = margin(2, 2, 2, 2),
    strip_text_size = 8
  )
)


theme_transfer <- theme(legend.text = element_blank(),
                        axis.text.x = element_blank(),
                        axis.text.y = element_blank(),
                        axis.title.x  = element_blank(),
                        axis.title.y  = element_blank(),
                        panel.grid.major = element_blank(),
                        panel.grid.minor = element_blank())

theme_subjects <- theme(legend.position = "top",
                        axis.text.x = element_blank(),
                        axis.text.y = element_blank(),
                        axis.title.x  = element_blank(),
                        axis.title.y  = element_blank(),
                        panel.grid.major = element_blank(),
                        panel.grid.minor = element_blank(),
                        # panel.border = element_rect(fill = NA),
                        panel.spacing = unit(5, "pt"))

update_geom_defaults("point", list(colour = "#ac0634"))
update_geom_defaults("line", list(colour = "#ac0634"))
update_geom_defaults("area", list(colour = "#ffffff", 
                                  fill   = "#ac0634"))
update_geom_defaults("rect", list(colour = "#ffffff", 
                                  fill   = "#ac0634"))
update_geom_defaults("density", list(# colour = "#f0f0f0", 
                                     fill   = "#ac0634"))
update_geom_defaults("bar", list(colour = "#ffffff", 
                                 fill   = "#ac0634"))
update_geom_defaults("col", list(colour = "#ffffff", 
                                 fill   = "#ac0634"))
update_geom_defaults("text", list(colour = "#ac0634"))
```

```{r init_data}
demo <- readRDS("data/demographics.rds")
training <- readRDS("data/trials-training.rds")
transfer <- readRDS("data/trials-transfer.rds")
stimprob <- readRDS("data/trials-probability.rds")

h1_bfs <- readr::read_csv("models/BFs.csv")
exclud_train <- readRDS("data/exclusions_training.rds")
exclud_trans <- readRDS("data/exclusions_transfer.rds")

extra_binom <- transfer %>% 
  filter(item == "transfer") %>% 
  group_by(subj_id, rules, blocked) %>% 
  summarize(
    k = sum(extrapolation),
    n = n(),
    p = k / n,
    .groups = "drop"
  ) %>% 
  mutate(
    combi = case_when(
      rules == "yes" & blocked == "yes" ~ "both",
      rules == "no"  & blocked == "yes" ~ "blocked",
      rules == "yes" & blocked == "no"  ~ "rules",
      TRUE ~ "neither"
    ),
    exab4 = ifelse(k > 3, 1, 0),
    exab5 = ifelse(k > 4, 1, 0),
    exab6 = ifelse(k > 5, 1, 0)
  )
```
